### ISSUE TITLE
请问能有偿指导搭建一下吗?

### ISSUE THREAD

**Issue by cathylogs** [lmx1989219/push-core#2]
大佬,请问能有偿指导搭建一下吗?我想基于您的项目做毕业设计

**Comment by alansfa** [comment]
+qq：285980382



---原始邮件---
发件人: "都是夜归人"<notifications@github.com&gt;
发送时间: 2020年4月21日(周二) 晚上7:27
收件人: "3kuai/hanbo-push"<hanbo-push@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [3kuai/hanbo-push] 请问能有偿指导搭建一下吗? (#2)




 
大佬,请问能有偿指导搭建一下吗?我想基于您的项目做毕业设计
